name: CI Build

on:
  push:
    branches:
      - mq2
  pull_request:
    branches:
      - mq2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Repository auschecken
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive  # wichtig, falls du Submodule verwendest

      # 2️⃣ Python einrichten
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ ESP-IDF einrichten
      - name: Set up ESP-IDF
        uses: espressif/install-esp-idf-action@v1
        with:
          version: v5.3.2

      # 4️⃣ Cache für Tools und Build-Artefakte
      - name: Cache ESP-IDF tools and build output
        uses: actions/cache@v4
        with:
          path: |
            ~/.espressif
            build
          key: ${{ runner.os }}-idf-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-idf-

      # 7️⃣ Build vorbereiten
      - name: Initialize project
        run: idf.py reconfigure

      # 8️⃣ Projekt bauen
      - name: Build project
        run: idf.py build

      # 9️⃣ Firmware erstellen
      - name: Upload firmware as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SmellIT-bin
          path: build/*.bin